// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TokenStorer is an autogenerated mock type for the TokenStorer type
type TokenStorer struct {
	mock.Mock
}

type TokenStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenStorer) EXPECT() *TokenStorer_Expecter {
	return &TokenStorer_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, token
func (_m *TokenStorer) Delete(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TokenStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TokenStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenStorer_Expecter) Delete(ctx interface{}, token interface{}) *TokenStorer_Delete_Call {
	return &TokenStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *TokenStorer_Delete_Call) Run(run func(ctx context.Context, token string)) *TokenStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenStorer_Delete_Call) Return(_a0 error) *TokenStorer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenStorer_Delete_Call) RunAndReturn(run func(context.Context, string) error) *TokenStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, token
func (_m *TokenStorer) Get(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenStorer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TokenStorer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenStorer_Expecter) Get(ctx interface{}, token interface{}) *TokenStorer_Get_Call {
	return &TokenStorer_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *TokenStorer_Get_Call) Run(run func(ctx context.Context, token string)) *TokenStorer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenStorer_Get_Call) Return(_a0 string, _a1 error) *TokenStorer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenStorer_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *TokenStorer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, token, userID
func (_m *TokenStorer) Save(ctx context.Context, token string, userID string) error {
	ret := _m.Called(ctx, token, userID)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TokenStorer_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type TokenStorer_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID string
func (_e *TokenStorer_Expecter) Save(ctx interface{}, token interface{}, userID interface{}) *TokenStorer_Save_Call {
	return &TokenStorer_Save_Call{Call: _e.mock.On("Save", ctx, token, userID)}
}

func (_c *TokenStorer_Save_Call) Run(run func(ctx context.Context, token string, userID string)) *TokenStorer_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TokenStorer_Save_Call) Return(_a0 error) *TokenStorer_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenStorer_Save_Call) RunAndReturn(run func(context.Context, string, string) error) *TokenStorer_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenStorer creates a new instance of TokenStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenStorer {
	mock := &TokenStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
