with-expecter: true
dir: internal/{{.PackageName}}/mocks
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/vladgrskkh/onerep-auth/internal/auth:
    interfaces:
      UserRepository:
      TokenStorer:
      OAuthAccountRepository:
