// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	serviceuser "github.com/vladgrskkh/onerep-auth/internal/service/user"

	user "github.com/vladgrskkh/onerep-auth/internal/domain/user"

	uuid "github.com/google/uuid"
)

// MockUserProfileService is an autogenerated mock type for the UserProfileService type
type MockUserProfileService struct {
	mock.Mock
}

type MockUserProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProfileService) EXPECT() *MockUserProfileService_Expecter {
	return &MockUserProfileService_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function with given fields: ctx, userID, requesterID
func (_m *MockUserProfileService) GetProfile(ctx context.Context, userID uuid.UUID, requesterID uuid.UUID) (user.UserProfile, error) {
	ret := _m.Called(ctx, userID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 user.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (user.UserProfile, error)); ok {
		return rf(ctx, userID, requesterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) user.UserProfile); ok {
		r0 = rf(ctx, userID, requesterID)
	} else {
		r0 = ret.Get(0).(user.UserProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, requesterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockUserProfileService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - requesterID uuid.UUID
func (_e *MockUserProfileService_Expecter) GetProfile(ctx interface{}, userID interface{}, requesterID interface{}) *MockUserProfileService_GetProfile_Call {
	return &MockUserProfileService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID, requesterID)}
}

func (_c *MockUserProfileService_GetProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, requesterID uuid.UUID)) *MockUserProfileService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserProfileService_GetProfile_Call) Return(_a0 user.UserProfile, _a1 error) *MockUserProfileService_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileService_GetProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (user.UserProfile, error)) *MockUserProfileService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, cmd
func (_m *MockUserProfileService) UpdateProfile(ctx context.Context, cmd serviceuser.UpdateProfileCommand) (user.UserProfile, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 user.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, serviceuser.UpdateProfileCommand) (user.UserProfile, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, serviceuser.UpdateProfileCommand) user.UserProfile); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(user.UserProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, serviceuser.UpdateProfileCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserProfileService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd serviceuser.UpdateProfileCommand
func (_e *MockUserProfileService_Expecter) UpdateProfile(ctx interface{}, cmd interface{}) *MockUserProfileService_UpdateProfile_Call {
	return &MockUserProfileService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, cmd)}
}

func (_c *MockUserProfileService_UpdateProfile_Call) Run(run func(ctx context.Context, cmd serviceuser.UpdateProfileCommand)) *MockUserProfileService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(serviceuser.UpdateProfileCommand))
	})
	return _c
}

func (_c *MockUserProfileService_UpdateProfile_Call) Return(_a0 user.UserProfile, _a1 error) *MockUserProfileService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileService_UpdateProfile_Call) RunAndReturn(run func(context.Context, serviceuser.UpdateProfileCommand) (user.UserProfile, error)) *MockUserProfileService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProfileService creates a new instance of MockUserProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProfileService {
	mock := &MockUserProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
