// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/vladgrskkh/onerep-auth/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockOAuthAccountRepository is an autogenerated mock type for the OAuthAccountRepository type
type MockOAuthAccountRepository struct {
	mock.Mock
}

type MockOAuthAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthAccountRepository) EXPECT() *MockOAuthAccountRepository_Expecter {
	return &MockOAuthAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, account
func (_m *MockOAuthAccountRepository) Create(ctx context.Context, account auth.OAuthAccount) (auth.OAuthAccount, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 auth.OAuthAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.OAuthAccount) (auth.OAuthAccount, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.OAuthAccount) auth.OAuthAccount); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Get(0).(auth.OAuthAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.OAuthAccount) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOAuthAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account auth.OAuthAccount
func (_e *MockOAuthAccountRepository_Expecter) Create(ctx interface{}, account interface{}) *MockOAuthAccountRepository_Create_Call {
	return &MockOAuthAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *MockOAuthAccountRepository_Create_Call) Run(run func(ctx context.Context, account auth.OAuthAccount)) *MockOAuthAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.OAuthAccount))
	})
	return _c
}

func (_c *MockOAuthAccountRepository_Create_Call) Return(_a0 auth.OAuthAccount, _a1 error) *MockOAuthAccountRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthAccountRepository_Create_Call) RunAndReturn(run func(context.Context, auth.OAuthAccount) (auth.OAuthAccount, error)) *MockOAuthAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProviderID provides a mock function with given fields: ctx, provider, providerUserID
func (_m *MockOAuthAccountRepository) FindByProviderID(ctx context.Context, provider auth.OAuthProvider, providerUserID string) (auth.OAuthAccount, error) {
	ret := _m.Called(ctx, provider, providerUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProviderID")
	}

	var r0 auth.OAuthAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.OAuthProvider, string) (auth.OAuthAccount, error)); ok {
		return rf(ctx, provider, providerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.OAuthProvider, string) auth.OAuthAccount); ok {
		r0 = rf(ctx, provider, providerUserID)
	} else {
		r0 = ret.Get(0).(auth.OAuthAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.OAuthProvider, string) error); ok {
		r1 = rf(ctx, provider, providerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthAccountRepository_FindByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProviderID'
type MockOAuthAccountRepository_FindByProviderID_Call struct {
	*mock.Call
}

// FindByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider auth.OAuthProvider
//   - providerUserID string
func (_e *MockOAuthAccountRepository_Expecter) FindByProviderID(ctx interface{}, provider interface{}, providerUserID interface{}) *MockOAuthAccountRepository_FindByProviderID_Call {
	return &MockOAuthAccountRepository_FindByProviderID_Call{Call: _e.mock.On("FindByProviderID", ctx, provider, providerUserID)}
}

func (_c *MockOAuthAccountRepository_FindByProviderID_Call) Run(run func(ctx context.Context, provider auth.OAuthProvider, providerUserID string)) *MockOAuthAccountRepository_FindByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.OAuthProvider), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthAccountRepository_FindByProviderID_Call) Return(_a0 auth.OAuthAccount, _a1 error) *MockOAuthAccountRepository_FindByProviderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthAccountRepository_FindByProviderID_Call) RunAndReturn(run func(context.Context, auth.OAuthProvider, string) (auth.OAuthAccount, error)) *MockOAuthAccountRepository_FindByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthAccountRepository creates a new instance of MockOAuthAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthAccountRepository {
	mock := &MockOAuthAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
