// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenStorer is an autogenerated mock type for the TokenStorer type
type MockTokenStorer struct {
	mock.Mock
}

type MockTokenStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStorer) EXPECT() *MockTokenStorer_Expecter {
	return &MockTokenStorer_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, token
func (_m *MockTokenStorer) Delete(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTokenStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenStorer_Expecter) Delete(ctx interface{}, token interface{}) *MockTokenStorer_Delete_Call {
	return &MockTokenStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockTokenStorer_Delete_Call) Run(run func(ctx context.Context, token string)) *MockTokenStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStorer_Delete_Call) Return(_a0 error) *MockTokenStorer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStorer_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, token
func (_m *MockTokenStorer) Get(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStorer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTokenStorer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenStorer_Expecter) Get(ctx interface{}, token interface{}) *MockTokenStorer_Get_Call {
	return &MockTokenStorer_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *MockTokenStorer_Get_Call) Run(run func(ctx context.Context, token string)) *MockTokenStorer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStorer_Get_Call) Return(_a0 string, _a1 error) *MockTokenStorer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStorer_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTokenStorer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, token, userID
func (_m *MockTokenStorer) Save(ctx context.Context, token string, userID string) error {
	ret := _m.Called(ctx, token, userID)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStorer_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenStorer_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID string
func (_e *MockTokenStorer_Expecter) Save(ctx interface{}, token interface{}, userID interface{}) *MockTokenStorer_Save_Call {
	return &MockTokenStorer_Save_Call{Call: _e.mock.On("Save", ctx, token, userID)}
}

func (_c *MockTokenStorer_Save_Call) Run(run func(ctx context.Context, token string, userID string)) *MockTokenStorer_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenStorer_Save_Call) Return(_a0 error) *MockTokenStorer_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStorer_Save_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTokenStorer_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenStorer creates a new instance of MockTokenStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStorer {
	mock := &MockTokenStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
