// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/vladgrskkh/onerep-auth/internal/service/auth"

	jwt "github.com/vladgrskkh/onerep-auth/internal/infrastructure/auth/jwt"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, cmd
func (_m *MockAuthService) Login(ctx context.Context, cmd auth.LoginCommand) (jwt.TokenPair, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 jwt.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginCommand) (jwt.TokenPair, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginCommand) jwt.TokenPair); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(jwt.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.LoginCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd auth.LoginCommand
func (_e *MockAuthService_Expecter) Login(ctx interface{}, cmd interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, cmd)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, cmd auth.LoginCommand)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.LoginCommand))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 jwt.TokenPair, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, auth.LoginCommand) (jwt.TokenPair, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, cmd
func (_m *MockAuthService) Logout(ctx context.Context, cmd auth.LogoutCommand) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.LogoutCommand) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd auth.LogoutCommand
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, cmd interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, cmd)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, cmd auth.LogoutCommand)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.LogoutCommand))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, auth.LogoutCommand) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, cmd
func (_m *MockAuthService) Refresh(ctx context.Context, cmd auth.RefreshCommand) (jwt.TokenPair, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 jwt.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RefreshCommand) (jwt.TokenPair, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.RefreshCommand) jwt.TokenPair); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(jwt.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.RefreshCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd auth.RefreshCommand
func (_e *MockAuthService_Expecter) Refresh(ctx interface{}, cmd interface{}) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, cmd)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(ctx context.Context, cmd auth.RefreshCommand)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.RefreshCommand))
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(_a0 jwt.TokenPair, _a1 error) *MockAuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(context.Context, auth.RefreshCommand) (jwt.TokenPair, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, cmd
func (_m *MockAuthService) Register(ctx context.Context, cmd auth.RegisterCommand) (jwt.TokenPair, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 jwt.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RegisterCommand) (jwt.TokenPair, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.RegisterCommand) jwt.TokenPair); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(jwt.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.RegisterCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd auth.RegisterCommand
func (_e *MockAuthService_Expecter) Register(ctx interface{}, cmd interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, cmd)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, cmd auth.RegisterCommand)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.RegisterCommand))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 jwt.TokenPair, _a1 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, auth.RegisterCommand) (jwt.TokenPair, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
