// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/vladgrskkh/onerep-auth/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserProfileRepository is an autogenerated mock type for the UserProfileRepository type
type MockUserProfileRepository struct {
	mock.Mock
}

type MockUserProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProfileRepository) EXPECT() *MockUserProfileRepository_Expecter {
	return &MockUserProfileRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserProfileRepository) FindByID(ctx context.Context, id uuid.UUID) (auth.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (auth.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) auth.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(auth.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserProfileRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserProfileRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserProfileRepository_FindByID_Call {
	return &MockUserProfileRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserProfileRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserProfileRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserProfileRepository_FindByID_Call) Return(_a0 auth.User, _a1 error) *MockUserProfileRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (auth.User, error)) *MockUserProfileRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockUserProfileRepository) Update(ctx context.Context, _a1 auth.User) (auth.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.User) (auth.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.User) auth.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(auth.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.User) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProfileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserProfileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 auth.User
func (_e *MockUserProfileRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockUserProfileRepository_Update_Call {
	return &MockUserProfileRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockUserProfileRepository_Update_Call) Run(run func(ctx context.Context, _a1 auth.User)) *MockUserProfileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.User))
	})
	return _c
}

func (_c *MockUserProfileRepository_Update_Call) Return(_a0 auth.User, _a1 error) *MockUserProfileRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProfileRepository_Update_Call) RunAndReturn(run func(context.Context, auth.User) (auth.User, error)) *MockUserProfileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProfileRepository creates a new instance of MockUserProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProfileRepository {
	mock := &MockUserProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
